# Zoptymalizowana konfiguracja BPR-MF
model: BPR
dataset: ml-1m
data_path: Datasets/
checkpoint_dir: '3_Evaluation/Saved/'

# Data settings
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp
load_col:
    inter: [user_id, item_id, rating, timestamp]

# Zmiany: Zwiększamy embedding_size dla lepszej pojemności modelu na 1M danych
epochs: 100               # Zwiększamy limit epok, early stopping i tak zadziała
train_batch_size: 4096
learning_rate: 0.001      # BPR dobrze działa na tym LR
embedding_size: 128       # Zwiększono z 64 na 128

# Evaluation settings
eval_args:
    split: {'RS': [0.8, 0.1, 0.1]}
    group_by: user
    order: RO
    mode: full
metrics: ['Recall', 'MRR', 'NDCG', 'Hit']
topk: 10
valid_metric: NDCG@10
device: CPU
