# Zoptymalizowana konfiguracja LightGCN
model: LightGCN
dataset: ml-1m
data_path: Datasets/
checkpoint_dir: '3_Evaluation/Saved/'

# Architektura
embedding_size: 128    # Zwiększono z 64 na 128
n_layers: 3            # Zwiększono z 2 na 3 (głębsza propagacja w grafie)
reg_weight: 1e-04      # Zwiększona regularyzacja dla większych embeddingów

# Data settings
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp
load_col:
    inter: [user_id, item_id, rating, timestamp]

# Training settings
epochs: 100
train_batch_size: 2048 # Mniejszy batch dla dokładniejszego spadku gradientu w GNN
learning_rate: 0.001
learner: adam

# Evaluation settings
eval_args:
    split: {'RS': [0.8, 0.1, 0.1]}
    group_by: user
    order: RO
    mode: full
metrics: ['Recall', 'MRR', 'NDCG', 'Hit']
topk: 10
valid_metric: NDCG@10
device: CPU
