# Konfiguracja modelu bazowego ItemKNN
model: ItemKNN
dataset: ml-100k
data_path: Datasets/
checkpoint_dir: '3_Evaluation/Saved/'

# Architektura
k: 100               # Liczba najbliższych sąsiadów

# Data settings
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp
load_col:
    inter: [user_id, item_id, rating, timestamp]
user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"

# Model nie jest trenowany w oparciu o stochastyczny spadek gradientu (nie wymaga epok i LR w tym samym wymiarze co deep learning)
# Evaluation settings
eval_args:
    split: {'RS': [0.8, 0.1, 0.1]}
    group_by: user
    order: RO
    mode: full
metrics: ['Recall', 'MRR', 'NDCG', 'Hit']
topk: 10
valid_metric: NDCG@10
device: CPU

checkpoint_dir: '3_Evaluation/Saved/'
